name: $(BuildID)

trigger:
- main

# variables:
#   user.email: "ganesh.b.ghadge@capgemini.com"
#   user.name: "DevOps"

variables:
- group: HelmPOC 

pool:
  vmImage: windows-latest

resources:
  repositories:
    - repository: ADPHelmRepository
      name: defra-adp-sandpit/adp-helm-repository
      endpoint: defra-adp-sandpit
      type: github
      ref: main  

steps:
  - checkout: self
    persistCredentials: true
    path: ADPHelmLibrary

  - checkout: ADPHelmRepository
    persistCredentials: true
    path: ADPHelmRepository  

  # - script: |
  #     git config user.email ${{variables['user.email']}}
  #     git config user.name ${{variables['user.name']}}
  #   displayName: 'Configure git credentials'

  # - powershell: |
  #     Write-Host 'Version Increment check'
  #     Write-Host 'Pipeline.Workspace = ' $(Pipeline.Workspace)
  #     Write-Host 'Agent.BuildDirectory = ' $(Agent.BuildDirectory)
  #     Write-Host 'Build.SourcesDirectory = ' $(Build.SourcesDirectory)
  #     Write-Host 'System.DefaultWorkingDirectory = ' $(System.DefaultWorkingDirectory)
  #   displayName: 'Verify Library Chart version incremented'

  # - powershell: |
  #     $lintPath = "$(Agent.BuildDirectory)/ADPHelmLibrary/adp-helm-library"
  #     Write-Host 'Printing helm version'
  #     Helm version
  #     Get-ChildItem
  #     Write-Host 'Helm lint: Path = ' $lintPath
  #     Helm lint $lintPath
  #     Write-Host 'Helm lint: End'
  #   displayName: 'Helm lint'   

  - task: PowerShell@2
    displayName: 'Publish Helm Chart'
    # condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    inputs:
      pwsh: true
      azurePowerShellVersion: latestVersion
      targetType: 'filePath'
      filePath: $(Agent.BuildDirectory)/ADPHelmLibrary/scripts/Publish-HelmLibrary.ps1
      arguments: >
        -HelmLibraryPath "$(Agent.BuildDirectory)\ADPHelmLibrary\adp-helm-library"
        -Token $(github-adpplatform-access-token)
      workingDirectory: $(System.DefaultWorkingDirectory) 